// packages/vue/src/CSSRuntimeProvider.vue
<script setup lang="ts">

import type { Config } from '@master/css'
import CSSRuntime from '@master/css-runtime'
import { onMounted, onBeforeUnmount, ref, provide } from 'vue'

const props = defineProps<{
    config?: Config | Promise<Config> | Promise<any>
    root?: Document | ShadowRoot
}>()

const runtimeCSS = ref()
const newCSSRuntime = ref()

onMounted(() => {
    if (typeof window === 'undefined') { return }
    if (!runtimeCSS.value) {
        const init = (resolvedConfig: Config | undefined) => {
            const existingCSSRuntime = (globalThis as any).runtimeCSSs.find((eachCSS: CSSRuntime) => eachCSS.root === props.root)
            if (existingCSSRuntime) {
                runtimeCSS.value = existingCSSRuntime
            } else {
                newCSSRuntime.value = new CSSRuntime(props.root, resolvedConfig).observe()
                runtimeCSS.value = newCSSRuntime.value
            }
        }

        if (props.config instanceof Promise) {
            (async () => {
                const configModule: any = await props.config
                init(configModule?.config || configModule?.default || configModule)
            })()
        } else {
            init(props.config)
        }
    } else if (!runtimeCSS.value.observing) {
        runtimeCSS.value.observe(props.root)
    }
})

onBeforeUnmount(() => {
    if (runtimeCSS.value && newCSSRuntime) {
        newCSSRuntime.value?.destroy()
    }
})

provide('css', runtimeCSS)

</script>

<template>
    <slot></slot>
</template>

// packages/react/src/CSSRuntimeProvider.tsx
'use client'

import type { Config } from '@master/css'
import { RuntimeCSS } from '@master/css-runtime'
import { useEffect, useLayoutEffect, createContext, useContext, useState } from 'react'

export const CSSRuntimeContext = createContext<RuntimeCSS | undefined>(undefined)
export const useCSSRuntime = () => useContext(CSSRuntimeContext)

export default function CSSRuntimeProvider({ children, config, root }: {
    children: React.ReactNode,
    config?: Config | Promise<any>,
    root?: Document | ShadowRoot
}) {
    const [runtimeCSS, setCSSRuntime] = useState<RuntimeCSS>();
    (typeof window !== 'undefined' ? useLayoutEffect : useEffect)(() => {
        let newCSSRuntime: RuntimeCSS | undefined = globalThis.runtimeCSSs?.find((eachCSS) => eachCSS.root === root)
        if (newCSSRuntime) {
            setCSSRuntime(newCSSRuntime)
        } else if (!runtimeCSS) {
            const init = (resolvedConfig?: Config) => {
                const existingCSS = globalThis.runtimeCSSs.find((eachCSS) => eachCSS.root === root)
                if (existingCSS) {
                    setCSSRuntime(existingCSS)
                } else {
                    newCSSRuntime = new RuntimeCSS(root, resolvedConfig).observe()
                    setCSSRuntime(newCSSRuntime)
                }
            }
            if (config instanceof Promise) {
                (async () => {
                    const configModule = await config
                    init(configModule?.config || configModule?.default || configModule)
                })()
            } else {
                init(config)
            }
        } else if (!runtimeCSS.observing) {
            runtimeCSS.observe()
        }
        return () => {
            newCSSRuntime?.destroy()
        }
    }, [config, root])
    return <CSSRuntimeContext.Provider value={runtimeCSS}>{children}</CSSRuntimeContext.Provider>
}
