// packages/svelte/src/LazyCSSProvider.svelte
<script lang="ts">
    import type { MasterCSS } from "@master/css";
    import { onMount, setContext } from "svelte";
    import { writable } from "svelte/store";
    import { lazyCSSSymbol } from "./lazy-css";
    export let config: Promise<any>;
    export let root = typeof document !== "undefined" ? document : null;
    const css = writable<MasterCSS>();
    onMount(async () => {
        if (!$css) {
            const [{ MasterCSS, initRuntime }, configModule] =
                await Promise.all([import("@master/css"), config]);
            const { instances } = MasterCSS;
            const existingCSS = instances.find(
                (eachCSS) => eachCSS.root === root
            );
            if (existingCSS) {
                css.set(existingCSS);
            } else {
                const resolvedConfig =
                    configModule?.config ||
                    configModule?.default ||
                    configModule;
                css.set(initRuntime(resolvedConfig));
            }
            return () => $css.destroy();
        }
    });
    setContext(lazyCSSSymbol, css);
</script>

<slot />

// packages/react/src/LazyCSSProvider.tsx
import type { MasterCSS, Config } from '@master/css'
import { ReactElement, useEffect, useState } from 'react'
import { Context, createContext, useContext } from 'react'

export const LazyCSSContext: Context<MasterCSS> = createContext<MasterCSS>(null)

export function useLazyCSS() {
    return useContext(LazyCSSContext)
}

export const LazyCSSProvider = ({
    children,
    config,
    root = typeof document !== 'undefined' ? document : null
}: {
    children: ReactElement,
    config?: Config | Promise<any>,
    root?: Document | ShadowRoot | null
}) => {
    const [css, setCSS] = useState<MasterCSS>()
    useEffect(() => {
        if (!css) {
            Promise.all([import('@master/css'), config])
                .then(([{ MasterCSS }, configModule]) => {
                    const { instances } = MasterCSS
                    const existingCSS = instances.find((eachCSS) => eachCSS.root === root)
                    if (existingCSS) {
                        setCSS(existingCSS)
                    } else {
                        const resolvedConfig = configModule.config || configModule.default || configModule
                        setCSS(new MasterCSS(resolvedConfig))
                    }
                })
        } else {
            return () => {
                css.destroy()
            }
        }
    }, [config, css, root])
    return <LazyCSSContext.Provider value={css}>{children}</LazyCSSContext.Provider>
}
