// packages/vue/src/ThemeServiceProvider.vue
<script setup lang="ts">

import { type Options, type ThemeValue, ThemeService } from 'theme-service'
import { onMounted, onBeforeUnmount, ref, provide, readonly } from 'vue'

const props = defineProps<{
    host?: HTMLElement,
    options?: Options
}>()

const themeService = ref<ThemeService>()
const current = ref<ThemeService['current']>()
const value = ref<ThemeService['value']>()

const onThemeChange = () => {
    if (themeService.value) {
        current.value = themeService.value.current
        value.value = themeService.value.value
    }
}

onMounted(() => {
    if (typeof window === 'undefined')
        return

    if (!themeService.value) {
        themeService.value = new ThemeService(props.options, props.host)
        themeService.value.init()
        current.value = themeService.value.current
        value.value = themeService.value.value
        themeService.value.host?.addEventListener('themeChange', onThemeChange)
    }
})

onBeforeUnmount(() => {
    if (themeService.value) {
        themeService.value.host?.removeEventListener('themeChange', onThemeChange)
        themeService.value.destroy(false)
    }
})

provide('theme-service', {
    current: readonly(current),
    value: readonly(value),
    switch: readonly((
        _value: ThemeValue,
        // options?: { store?: boolean, emit?: boolean }
    ) => {
        if (themeService.value) {
            themeService.value.switch(_value)
            current.value = themeService.value.current
            value.value = themeService.value.value
        }
    })
})

</script>

<template>
    <slot></slot>
</template>

// packages/react/src/ThemeServiceProvider.tsx
'use client'

import { Options, ThemeValue, ThemeService } from 'theme-service'
import { Context, createContext, DependencyList, EffectCallback, useCallback, useContext, useEffect, useLayoutEffect, useMemo, useState } from 'react'

const useIsomorphicEffect: (effect: EffectCallback, deps?: DependencyList) => void =
    typeof window !== 'undefined' ? useLayoutEffect : useEffect

export const ThemeServiceContext: Context<ThemeService> = createContext<ThemeService>(null)

export function useThemeService() {
    return useContext(ThemeServiceContext)
}

export function ThemeServiceProvider({
    options,
    host,
    children
}: {
    host?: HTMLElement,
    options?: Options,
    children: JSX.Element,
}) {
    const themeService = useMemo(() => new ThemeService({ ...options, init: false }, host), [options, host])
    // Make React hook theme members
    const [current, setCurrent] = useState<string>(themeService.current)
    const [value, setValue] = useState<ThemeValue>(themeService.value)

    const switchValue = useCallback((value: ThemeValue, options?: {
        store?: boolean;
        emit?: boolean;
    }) => {
        themeService.switch(value)
        setCurrent(themeService.current)
        setValue(themeService.value)
    }, [themeService])

    const onThemeChange = useCallback(() => {
        setCurrent(themeService.current)
        setValue(themeService.value)
    }, [themeService])

    useIsomorphicEffect(() => {
        themeService.init()
        setCurrent(themeService.current)
        setValue(themeService.value)
        themeService.host.addEventListener('themeChange', onThemeChange)
        return () => {
            themeService.host.removeEventListener('themeChange', onThemeChange)
            themeService.destroy()
        }
    }, [onThemeChange, themeService])

    return <ThemeServiceContext.Provider value={{ ...themeService, value, current, switch: switchValue } as ThemeService}>{children}</ThemeServiceContext.Provider>
}

export default ThemeServiceProvider
