// packages/svelte/src/CSSProvider.svelte
<script lang="ts">
    import { MasterCSS, initRuntime, type Config } from "@master/css";
    import { onMount, setContext } from "svelte";
    import { writable } from "svelte/store";
    import { cssSymbol } from "./css";
    export let config: Config | Promise<Config> | Promise<any>;
    export let root: Document | ShadowRoot | null =
        typeof document !== "undefined" ? document : null;
    const css = writable<MasterCSS>(
        MasterCSS.instances.find((eachCSS) => eachCSS.root === root)
    );
    onMount(async () => {
        let newCSS: MasterCSS;
        if (!$css) {
            const init = (resolvedConfig?: Config) => {
                const existingCSS = MasterCSS.instances.find(
                    (eachCSS) => eachCSS.root === root
                );
                if (existingCSS) {
                    css.set(existingCSS);
                } else {
                    newCSS = initRuntime(resolvedConfig);
                    css.set(newCSS);
                }
            };
            if (config instanceof Promise) {
                (async () => {
                    const configModule = await config;
                    init(
                        configModule?.config ||
                            configModule?.default ||
                            configModule
                    );
                })();
            } else {
                init(config);
            }
        } else if (!$css.observing) {
            $css.observe(root);
        }
        return () => {
            newCSS?.destroy();
        };
    });
    setContext(cssSymbol, css);
</script>

<slot />

// packages/vue/src/CSSProvider.vue
<script setup lang="ts">

import { MasterCSS, initRuntime, type Config } from '@master/css'
import { onMounted, onBeforeUnmount, ref, provide } from 'vue'

const props = defineProps<{
    config?: Config | Promise<Config> | Promise<any>
    root?: Document | ShadowRoot
}>()

const css = ref()
const newCSS = ref()

onMounted(() => {
    if (typeof window === 'undefined') { return }
    if (!css.value) {
        const init = (resolvedConfig: Config | undefined) => {
            const existingCSS = MasterCSS.instances.find((eachCSS: any) => eachCSS.root === props.root)
            if (existingCSS) {
                css.value = existingCSS
            } else {
                newCSS.value = initRuntime(resolvedConfig)
                css.value = newCSS.value
            }
        }

        if (props.config instanceof Promise) {
            (async () => {
                const configModule: any = await props.config
                init(configModule?.config || configModule?.default || configModule)
            })()
        } else {
            init(props.config)
        }
    } else if (!css.value.observing) {
        css.value.observe(props.root)
    }
})

onBeforeUnmount(() => {
    if (css.value && newCSS) {
        newCSS.value?.destroy()
    }
})

provide('css', css)

</script>

<template>
    <slot></slot>
</template>
