// packages/svelte/src/CSSRuntimeProvider.svelte
<script lang="ts">
    import type { Config } from "@master/css";
    import CSSRuntime from "@master/css-runtime";
    import { onMount, setContext } from "svelte";
    import { writable } from "svelte/store";
    import { cssRuntimeSymbol } from "./css-runtime";
    export let config: Config | Promise<Config> | Promise<any>;
    export let root: Document | ShadowRoot | undefined = undefined;
    const runtimeCSS = writable<CSSRuntime>();
    onMount(() => {
        let newCSSRuntime: CSSRuntime;
        if (!$runtimeCSS) {
            const init = (resolvedConfig?: Config) => {
                const existingCSSRuntime = (globalThis as any).runtimeCSSs.find(
                    (eachCSS: CSSRuntime) => eachCSS.root === root
                );
                if (existingCSSRuntime) {
                    runtimeCSS.set(existingCSSRuntime);
                } else {
                    newCSSRuntime = new CSSRuntime(root, resolvedConfig).observe();
                    runtimeCSS.set(newCSSRuntime);
                }
            };
            if (config instanceof Promise) {
                (async () => {
                    const configModule = await config;
                    init(
                        configModule?.config ||
                            configModule?.default ||
                            configModule
                    );
                })();
            } else {
                init(config);
            }
        } else if (!$runtimeCSS.observing) {
            $runtimeCSS.observe();
        }
        return () => {
            newCSSRuntime?.destroy();
        };
    });
    setContext(cssRuntimeSymbol, runtimeCSS);
</script>

<slot />

// packages/vue/src/CSSRuntimeProvider.vue
<script setup lang="ts">

import type { Config } from '@master/css'
import CSSRuntime from '@master/css-runtime'
import { onMounted, onBeforeUnmount, ref, provide } from 'vue'

const props = defineProps<{
    config?: Config | Promise<Config> | Promise<any>
    root?: Document | ShadowRoot
}>()

const runtimeCSS = ref()
const newCSSRuntime = ref()

onMounted(() => {
    if (typeof window === 'undefined') { return }
    if (!runtimeCSS.value) {
        const init = (resolvedConfig: Config | undefined) => {
            const existingCSSRuntime = (globalThis as any).runtimeCSSs.find((eachCSS: CSSRuntime) => eachCSS.root === props.root)
            if (existingCSSRuntime) {
                runtimeCSS.value = existingCSSRuntime
            } else {
                newCSSRuntime.value = new CSSRuntime(props.root, resolvedConfig).observe()
                runtimeCSS.value = newCSSRuntime.value
            }
        }

        if (props.config instanceof Promise) {
            (async () => {
                const configModule: any = await props.config
                init(configModule?.config || configModule?.default || configModule)
            })()
        } else {
            init(props.config)
        }
    } else if (!runtimeCSS.value.observing) {
        runtimeCSS.value.observe(props.root)
    }
})

onBeforeUnmount(() => {
    if (runtimeCSS.value && newCSSRuntime) {
        newCSSRuntime.value?.destroy()
    }
})

provide('css', runtimeCSS)

</script>

<template>
    <slot></slot>
</template>
